### ISSUE TITLE
allOf, anyOf, oneOf

### ISSUE THREAD

**Issue by Quafadas** [cchandurkar/json-schema-to-case-class#24]
I can see that this repo hasn't been updated in a while. 

Are there plans to support these keywords. Do you have a solution sketch? I may try a PR if there is still interest...

**Comment by dfanesiDB** [comment]
@Quafadas I am interested in this too, but not very familiar with javascript. Did you find any alternative solution to this?

**Comment by Quafadas** [comment]
@dfanesiDB Well, I had a stab at a PR in this repository, but to be honest, concluded it would be pretty hard. 

I ended up over here; 
https://github.com/quicktype/quicktype/pull/1932

I claim, that PR works. It generated case classes for the Vega schema at any rate :-). 
https://github.com/Quafadas/dedav4s/tree/main/generated/shared/src/main/scala/viz/dsl

If you checkout that repo / branch and build the QuickType CLI from source, you should be able to generate case classes for scala 3 / circe. I have the hope, that the maintainers will merge it. 

I'm not 100% sure about the treatment of enums, and would love to add upickle to that PR... but for now it was enough for me! 

I will say that QuickType appears to be rather well designed. It would not be tooooo hard, to add scala 2 support.
