### ISSUE TITLE
Asserts generated for Options use .get

### ISSUE THREAD

**Issue by aheiska** [cchandurkar/json-schema-to-case-class#32]
For example schema in previous bug produces

`assert(temporalScore.get >= 0, "`temporalScore.get` must be greater than or equal to 0")`

Suggestion for assertion:

`assert(temporalScore.fold(true)(_ >= 0), "`temporalScore` must be greater than or equal to 0")`

**Comment by cchandurkar** [comment]
I was thinking the same and have some WIP. I was more thinking of something like:
```
asssert( temporalScore.contains( _ >= 0) )
```
^ That seems more readable and fault tolerant.

**Comment by aheiska** [comment]
Yeah `fold` is too verbose here,`.contains`however takes a value not a function. I think `.forall` would be the correct choice.

**Comment by cchandurkar** [comment]
Oh my bad. I think meant `.exists()`

**Comment by aheiska** [comment]
I think assertion parameter should be true for `None` (i.e. None should be accepted value). You want `.forall`. Demo:

```
@ val opt: Option[Int] = None 
opt: Option[Int] = None

@ opt.forall(_ >= 0) 
res1: Boolean = true

@ opt.exists(_ >= 0) 
res2: Boolean = false
```

**Comment by cchandurkar** [comment]
Changes have been reflected in [online editor](https://cchandurkar.github.io/json-schema-to-case-class/?q=23898ds7f) as well.
