### ISSUE TITLE
Idea: command-line

### ISSUE THREAD

**Issue by FabHof** [cchandurkar/json-schema-to-case-class#40]
first of all: thanks for this great tool!

I was thinking that it would be nice to be able to run this tool via npx.
I am thinking of being able to do something like:
```
npx json-schema-to-case-class some-schema.json --topLevelCaseClassName SomeCaseClass--output SomeCaseClass.scala
```

I think the cli options can easily be mapped to the configuration.

**Comment by cchandurkar** [comment]
I actually had a CLI WIP branch in my old repo but never finished working on. Thanks for bringing this up. Just released this feature: https://github.com/cchandurkar/json-schema-to-case-class/releases/tag/v1.6.1
